{% set version = "10.2" %}

package:
    name: keyring
    version: {{ version }}

source:
    fn: keyring-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/k/keyring/keyring-{{ version }}.tar.gz
    sha256: bf49be09b31db401791bde1799da30d6926e7de2f0fb836c3dfc85aa5538a572
    patches:
        - verbose-tests.patch
        - use-pywin32.patch

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - keyring=keyring.cli:main
    skip: True  # [linux]

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm >=1.9
        - pywin32  # [win]
    run:
        - python
        - pywin32  # [win]

test:
    imports:
        - keyring
        - keyring.backends
        - keyring.tests
        - keyring.tests.backends
        - keyring.util
    commands:
        - keyring --help
        - cd {{ environ.SRC_DIR }} && python setup.py test -v
    requires:
        - pytest >=2.8
        - pytest-runner
        - setuptools_scm >=1.9

about:
    home: https://github.com/jaraco/keyring
    license: Python Software Foundation or MIT
    summary: 'Store and access your passwords safely.'

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
