{% set name = "keyring" %}
{% set version = "21.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/keyring-{{ version }}.tar.gz
  sha256: c53e0e5ccde3ad34284a40ce7976b5b3a3d6de70344c3f8ee44364cc340976ec

build:
  number: 4
  skip: true   # [py2k]
  entry_points:
    - keyring=keyring.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm >=3.4.1
  run:
    - python
    - importlib-metadata  # [py<38]
    - jeepney >=0.4.2  # [linux]
    - pywin32-ctypes !=0.1.0,!=0.1.1  # [win]
    - secretstorage >=3  # [linux]

test:
  requires:
    - pip
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  commands:
    - pip check
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: MIT
  license_file: LICENSE
  summary: Store and access your passwords safely

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ccordoba12
