{% set version = "21.1.0" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: 1f393f7466314068961c7e1d508120c092bd71fa54e3d93b76180b526d4abc56

build:
  number: 0
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - keyring = keyring.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python
    - pywin32-ctypes  # [win]
    - entrypoints
    - secretstorage  # [linux]
    - importlib_metadata  # [py<38]

test:
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  commands:
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: Python Software Foundation or MIT
  license_file: LICENSE
  summary: 'Store and access your passwords safely'

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ccordoba12
