{% set version = "21.5.0" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: 207bd66f2a9881c835dad653da04e196c678bf104f8252141d2d3c4f31051579

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - keyring = keyring.cli:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm >=3.4.1
    - setuptools >=42
    - toml
  run:
    - python
    - pywin32-ctypes  # [win]
    - secretstorage >=3.2  # [linux]
    - importlib_metadata >=1  # [py<38]
    - jeepney >=0.4.2  # [linux]

test:
  requires:
    - pip
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  commands:
    - pip check
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: MIT
  license_file: LICENSE
  summary: Store and access your passwords safely

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ccordoba12
