{% set version = "21.2.0" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: 197fd5903901030ef7b82fe247f43cfed2c157a28e7747d1cfcf4bc5e699dd03

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - keyring = keyring.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=3.4.1
    - setuptools >=42
    - toml
  run:
    - python
    - pywin32-ctypes  # [win]
    - entrypoints
    - secretstorage  # [linux]
    - importlib_metadata  # [py<38]

test:
  requires:
    - pip
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  commands:
    - pip check
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: Python Software Foundation or MIT
  license_file: LICENSE
  summary: Store and access your passwords safely

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ccordoba12
