{% set version = "23.4.0" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: 88f206024295e3c6fb16bb0a60fb4bb7ec1185629dc5a729f12aa7c236d01387

build:
  number: 1
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - keyring = keyring.cli:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm >=3.4.1
    - setuptools >=42
    - toml
  run:
    - python
    - pywin32-ctypes  # [win]
    - secretstorage >=3.2  # [linux]
    - importlib_metadata >=3.6
    - jeepney >=0.4.2  # [linux]

test:
  requires:
    - pip
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  commands:
    - pip check
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: MIT
  license_file: LICENSE
  summary: Store and access your passwords safely
  dev_url: https://github.com/jaraco/keyring
  doc_url: https://pypi.org/project/keyring/

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - ccordoba12
    - varlackc
