{% set version = "10.4.0" %}

package:
    name: keyring
    version: {{ version }}

source:
    fn: keyring-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
    sha256: 901a3f4ed0dfba473060281b58fd3b649ce70f59cb34a9cf6cb5551218283b26
    patches:
        - verbose-tests.patch
        - use-pywin32.patch

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - keyring=keyring.cli:main

requirements:
    build:
        - python
        - setuptools
        - setuptools_scm >=1.15.0
        - pywin32  # [win]
    run:
        - python
        - pywin32  # [win]

test:
    source_files:
        - tests
    imports:
        - keyring
        - keyring.backends
        - keyring.tests
        - keyring.tests.backends
        - keyring.util
    commands:
        - py.test -v tests
        - keyring --help
    requires:
        - pytest >=2.8
        - pytest-runner
        - setuptools_scm >=1.15.0

about:
    home: https://github.com/jaraco/keyring
    license: Python Software Foundation or MIT
    summary: 'Store and access your passwords safely.'
    description: |
      the python keyring lib provides a easy way to access the system keyring
      service from python.  it can be used in any application that needs safe
      password storage.
    doc_url: https://pypi.org/project/keyring/
    doc_source_url: https://github.com/jaraco/keyring/blob/master/readme.rst

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
